services:
  server:
    build:
      context: .
    container_name: elodrinksbackend-api
    image: elodrinksbackend
    ports:
      - 8000:8000
    depends_on:
      - supabase-db
    environment:
      - POSTGRES_URI=postgresql://postgres:postgres@supabase-db:5432/postgres
    env_file:
      - .env

  supabase-db:
    image: supabase/postgres:17.4.1.042
    container_name: elodrinksbackend-supabase-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    tmpfs:
      - /var/lib/postgresql/data
