name: Run Postman Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Newman
      run: npm install -g newman

    - name: Run Postman Collection
      run: |
        newman run tests/EloDrinksBackend Collection Tests.postman_collection.json \
          -e tests/prod.postman_environment.json \
          --delay-request 100 \
          --reporters cli,json \
          --reporter-json-export newman-report.json
