name: Run Postman Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Create .env file from GitHub Secrets
        run: |
          cat <<EOF > .env
          API_KEY=${{ secrets.API_KEY }}
          SECRET_KEY=${{ secrets.SECRET_KEY }}
          ALGORITHM=${{ secrets.ALGORITHM }}
          ACCESS_TOKEN_EXPIRE_MINUTES=${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}
          MONGO_URI=${{ secrets.MONGO_URI }}
          MONGO_DATABASE=${{ secrets.MONGO_DATABASE }}
          POSTGRES_URI=${{ secrets.POSTGRES_URI }}
          CLOUDINARY_NAME=${{ secrets.CLOUDINARY_NAME }}
          CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}
          CLOUDINARY_FOLDER=${{ secrets.CLOUDINARY_FOLDER }}
          CLOUDINARY_DEFAULT_URL=${{ secrets.CLOUDINARY_DEFAULT_URL }}
          REDIS_HOST=${{ secrets.REDIS_HOST }}
          REDIS_PORT=${{ secrets.REDIS_PORT }}
          REDIS_USERNAME=${{ secrets.REDIS_USERNAME }}
          REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
          APP_HOST=http://localhost:8000/
          EOF
 
      - name: Start API with Makefile
        run: make docker

      - name: Install Newman with HTML reporter
        run: npm install -g newman newman-reporter-html

      - name: Run Postman tests and generate HTML report
        run: |
          newman run tests/EloDrinksBackend_Collection_Tests.postman_collection.json \
            -e tests/local.postman_environment.json \
            --reporters cli,html \
            --reporter-html-export tests/reports/report.html

      - name: Upload HTML report as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: postman-report
          path: tests/reports/report.html
